#!/usr/bin/env bash
set -e

days=( $(gh api graphql -f query='{
  viewer {
    contributionsCollection {
      contributionCalendar {
        weeks {
          contributionDays {
            color
          }
        }
      }
    }
  }
}' --cache 24h --jq '..|.color?' | grep .) )
 
style=block
if [ "$1" = "-s" ] || [ "$1" = "--style" ]; then
  style="$2"
fi

case "$style" in
block)
  block_full="█"
  block_empty="$block_full";;
square)
  block_full="◼︎"
  block_empty="$block_full";;
dot)
  block_full="•"
  block_empty="$block_full";;
shade)
  block_full="▒"
  block_empty="░";;
fisheye)
  block_full="◉"
  block_empty="●";;
diamond)
  block_full="♦︎"
  block_empty="$block_full";;
plus)
  block_full="✚"
  block_empty="•";;
*)
  echo "error: style '$style' not recognized" >&2
  echo "available styles: block square dot shade fisheye diamond plus" >&2
  exit 1;;
esac

char() {
  if [ "$1" = "#ebedf0" ]; then
    echo "$block_empty"
  else
    echo "$block_full"
  fi
}

for d in $(seq 0 6); do
  for w in $(seq 0 51); do
    hex="${days[w*7+d]}"
    printf "\e[38;2;%d;%d;%dm%s\e[m " "$((16#${hex:1:2}))" "$((16#${hex:3:2}))" "$((16#${hex:5:2}))" "$(char "$hex")"
  done
  printf "\n"
done
printf "\n"
